### PR TITLE
Fixing some trash drop recording and displaying issues.

### LINKED ISSUE #373: Town Details entered in Admin Tool not showing in App
The app is pulling from Comments, not Town Description. It needs to pull from Town Description.

### PR DESCRIPTION
**Pull request by nfloersch**
Fix for trash drops not saving #369, and for trash drops not showing on trash map #370.
Also fixed trash map pin toggler to not obscure Apple Maps compass in top-right corner #371.
Also changed home screen background to dark green.
Updated to v5.0.23

### CODE REVIEW

File: data-sources/firebase-data-layer.js [hunk 1]
```diff
@@ -649,7 +649,15 @@ export function removeTeamRequest(teamId: string, teamMember: UserType): Promise
...
-    return db.collection("trashDrops").add(deconstruct({ ...trashDrop, location: { ...trashDrop.location } }));
+    let newDrop = deconstruct(
+        { 
+            ...trashDrop, 
+            location: { 
+                ...trashDrop.location 
+            } 
+        }
+    );
+    return db.collection("trashDrops").add(newDrop);
```
Comment (doub1ejack) [inline data-sources/firebase-data-layer.js:660]: @nfloersch Do you understand why John's using `deconstruct()` here?  It looks like it just stringifies & parses an object.  If there were tricky types involved, or weird prototypes, that might make sense.  Do you know the purpose?

File: components/trash-drop-form/trash-drop-form.js [hunk 2]
```diff
@@ -180,10 +180,10 @@ export const TrashDropForm = ({ teamOptions, onSave, currentUser, townData, tras
     // setRefKey(0);
 
     const clickOnMap = (loc) => {
-        drop.coordinates = loc;
-        drop.location = loc;
+        //drop.coordinates = loc;
+        //drop.location = loc;
```
Comment (doub1ejack) [inline components/trash-drop-form/trash-drop-form.js:206]: What's up here? If you're temporarily commenting these out, would you add a comment explaining when to restore them?

File: components/trash-drop-form/trash-drop-form.js [hunk 3]
```diff
@@ -180,10 +180,10 @@ export const TrashDropForm = ({ teamOptions, onSave, currentUser, townData, tras
...
         // alert(JSON.stringify(loc));
-        setDrop(drop);
+        setDrop({ ...drop, collectionSiteId: null, location: {...(drop.location), coordinates: loc} });
```
Comment (doub1ejack) [inline components/trash-drop-form/trash-drop-form.js:208]: I don't see why the argument to setDrop is constructed this way quite yet.. Could you add a comment explaining why the collectionSiteId needs to be null?  And I guess I'm not seeing why the location uses `loc` coordinates to overwrite (?) the drop location - what's going on there?

File: libs/green-up-day-calucators.js [hunk 4]
```diff
@@ -64,14 +64,16 @@ export const getCurrentGreenUpDay = (today?: Date): Date => {
 export const daysUntilCurrentGreenUpDay = (today?: TodayType): number => {
     const myToday = today === null ? moment() : moment(today);
     const greenUpDay = moment(getNextGreenUpDay());
-    return greenUpDay.diff(myToday, "days");
+    //return greenUpDay.diff(myToday, "days");
```
Comment (doub1ejack) [inline libs/green-up-day-calucators.js:67]: This is separate from the trash drop stuff right?  I assume this is to let us QA the app as if it was green up day?  If so, I'd love to merge this work with #366.  It would be great if the _**non-production**_ apps **_always_** allowed us to pretend it was green up day.  

If we add the production-env flags from 366 to this, then we can safely deploy the same work to any environment instead of maintaining a "dev" branch and a "prod" branch (or similar).

File: screens/home-screen/index.js [hunk 5]
```diff
@@ -236,20 +236,20 @@ const HomeScreen = ({ actions, currentUser, navigation, myTeams, teams }: PropsT
         ));
 
         return (
-            <GridRow style={ { backgroundColor: "#d5dbd5" } } columns={ 2 }>
+            <GridRow style={ { backgroundColor: constants.colorBackgroundDark } } columns={ 2 }>
```
Comment (doub1ejack) [inline screens/home-screen/index.js:239]: ❤️ !  I'm super in favor of replacing any "magic" styling with centralized constants/styles.  Thanks for this!

File: screens/trash-map-screen/index.js [hunk 6]
```diff
@@ -300,8 +300,14 @@ const mapStateToProps = (state: Object): Object => {
...
-    const drops = Object.values(state.trashTracker.trashDrops || [])
-        .filter((drop: any): boolean => Boolean(drop.location && drop.location.longitude && drop.location.latitude));
+    const drops = Object.values(state.trashTracker.trashDrops).filter(
+        (drop: any): boolean => Boolean(
+            drop.location && 
+            drop.location.coordinates && 
+            drop.location.coordinates.longitude && 
+            drop.location.coordinates.latitude
+        )
+    );
```
Comment (doub1ejack) [inline screens/trash-map-screen/index.js:347]: My js syntax is still a little spotty: without the ` || []` does this new code fail if `state.trashTracker.trashDrops` is null?  Or is it impossible for trashDrops to be null?

**Review by doub1ejack — APPROVED** [review]
I love all of this.  Thanks Nick. 

I did leave a handful of requests for clarifying comments, and one potential (?) bug flag but once you review these comments please feel free to fix/skip/proceed as you see fit.  Thanks for the work & for the PR 👍

File: data-sources/firebase-data-layer.js (hunk 1 above)
Comment (nfloersch) [reply data-sources/firebase-data-layer.js:660]: The only reason I multi-lined the code was to help set breakpoints in the debugging... so I could verify what was getting passed in and then what the output of the deconstruct() actually looked like. In the end I did not change his code's function here.

As for why the deconstruct... I think it is style, but also, I think he stubs out a lot of stuff up front, and fills in later. So the deconstruct allowed him to have the object be refined and expanded over time without having to set it in stone here the first time he wrote this. That's my guess.

File: libs/green-up-day-calucators.js (hunk 4 above)
Comment (nfloersch) [reply libs/green-up-day-calucators.js:67]: Yeah I like the idea of using the "production detection" code you had in #366 but putting it into the green-up-day-calculators.js file instead... that would make a lot of sense. I think I'll probably merge this, then take your code for determining the channel of the app in my next update to bring the two ideas together.

File: screens/trash-map-screen/index.js (hunk 6 above)
Comment (nfloersch) [reply screens/trash-map-screen/index.js:347]: Oh, no, that just got removed when I was working through why that whole line 303-304 thing didn't seem to be working. Forgot to put it back in. Although it is an edge case, it is possible for trashDrops to be null. I think mostly if I delete the collection from the database entirely... the first person to load the app after would hit the edge case. So I'll throw that back in.

File: screens/home-screen/index.js (hunk 5 above)
Comment (nfloersch) [reply screens/home-screen/index.js:239]: The whole #d5dbd5 color was very strange... this is the color of the background beyond the home screen's tiles. It was a gray color (well, literally #d5dbd5). It has been driving me nuts stylistically for a while. I didn't see it defined in the themes or styles for the app, which was odd. It seemed to be hard coded for the color in that screen. Anyway, a lot of the app's colors/styles are given better names in the "constants", so I grabbed one that seemed to look better and that was also, by nature of being a constant, more part of the theme.
